[main]
    certname = puppet-server
    server = puppet-server
    environment = production
    runinterval = 30m

[master]
    dns_alt_names = puppet,puppet-server

[agent]
    server = puppet-server